.TH "CDV-AGENT" 1 "Dec 1 2005"
.SH NAME 
cdv\-agent \- codeville authentication agent
.SH SYNOPSIS 
.nf
.B cdv\-agent [\-a \fIbind_address\fP] [\-c | \-s] [\-t life] [\-d] [command [args ...]]
.B cdv\-agent [\-c | \-s] \-k
.fi

.SH DESCRIPTION 

\fBcdv-agent\fP is a agent for holding passwords for a codeville server, so
that users don't need to type passwords so much.  The options are taken 
from the \fBssh\-agent\fP and perform the same purpose.

.SH SEE ALSO 
.BR ssh-agent (1), 
.BR cdvserver (1), 
.BR cdv (1),
.UR http://www.codeville.com
.BR http://www.codeville.com

.SH AUTHOR
This manual page was written by Michael Janssen <jamuraa@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
