.TH "CDVPASSWD" 1 "Dec 1 2005"
.SH NAME
cdvpasswd \- adds, removes, or sets passwords for users of a cdv server.
.SH SYNOPSIS
.B cdvpasswd [ add | set | delete ] \fIusername\fP
.SH OPTIONS
.TP
.B "\-c <filename>"
Specify the config file which the server is running on. 
.TP 
.B "\-f <filename>"
Specify the password file to modify.

.SH SEE ALSO 
.BR cdv (1), 
.BR cdvserver (1), 
.UR http://www.codeville.org/
.BR http://www.codeville.org/

.SH AUTHOR
This manual page was written by Michael Janssen <jamuraa@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
