.TH "CDVUPGRADE" 1 "Aug 1 2006"
.SH NAME
cdvupgrade \- upgrades codeville repositories and server directories
.SH SYNOPSIS
.B cdvupgrade [ \fI<path>\fP ]
.SH OPTIONS
.TP
.B "<path>"
Specify the directory to upgrade.  This directory can be the base directory
of either a checked-out repository or a server instance.

.SH SEE ALSO 
.BR cdv (1), 
.BR cdvserver (1), 
.UR http://www.codeville.org/
.BR http://www.codeville.org/

.SH AUTHOR
This manual page was written by Michael Janssen <jamuraa@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
